### ISSUE TITLE
Is there a way to use this with Nodejs 10.x - ES5? 

### ISSUE THREAD

**Issue by eflyerman** [gmmorris/simmerjs#13]
I would love to use this for an AWS Lambda I'm creating.  I'm stuck in ES5 (Node 10.13).  10.13 only supports ES6 with --experimental-mode flag.  I haven't found a way to set that for Lambda.

I've tried various iterations with both the module and the drop in without any success... 

 **All cause SyntaxError: Unexpected token because of ES6 Compatibility**
```
import Simmer from 'simmerjs';
import Simmer from './node_modules/simmerjs/dist/simmer.js';
import { Simmer } from './simmerjs';
import Simmer from 'simmer.js'
import Simmer from "./node_modules/simmerjs/dist/simmer.js";
```
 **This causes a "window is undefined" error message**
```
const Simmer = require("./node_modules/simmerjs/dist/simmer.js");
```

 **this causes "the SyntaxError: Unexpected token" error message because of the imports in the header**
```
const Simmer = require("./node_modules/simmerjs/modules/simmer.js");
```
 **This loads fine but throws a "TypeError: Simmer is not a constructor" error on const simmer = new Simmer(jsdom_window)**
```
const Simmer = require("simmerjs");
//
```
Hope you have some thoughts about what I haven't tried.  My next step is to try to transpile the module to ES5 with babel.

Thanks in advance,
E

**Comment by gmmorris** [comment]
Hi E,
You should definitely be able to consume Simmer using CommonJS, no need for ES modules, but as it's designed to be used by modules, you need to tell Node that you want to use the *default* export.

Note though that Simmer needs an HTML document to work on to figure out what the selector needs to be, so in Node you'll need to create an HTML document and tell Simmer to use it, and you can use a library like JSDOM to achieve this.

The example bellow works:
```js
const Simmer = require('simmerjs').default; // Use commonJS to get default export

// create an HTML document to use as our reference for what the page looks like
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

// instanciate Simmer so it knows not to use a global Window, but rather the JSDom document
const simmer = new Simmer(dom.window.document);

// find the element we wish to generate a selector for
const paragraph = dom.window.document.querySelector("p");

// Ask simmer to generate a selector for it
console.log(simmer(paragraph)); // prints the selector "P"
```

**Comment by gmmorris** [comment]
If you have any other issues, feel free to ask and I'll try and help.

**Comment by eflyerman** [comment]
Perfect!  I just needed the .default.  I spent hours trying to resolve this.  Thank you for the quick response.

**Comment by gmmorris** [comment]
My pleasure 😁
