### ISSUE TITLE
Library still up to date?

### ISSUE THREAD

**Issue by theianjohnson** [gmmorris/simmerjs#8]
Hey! Found your library through your Medium post and it's right up the alley of what I'm looking for - but I also see your big warning on the read me and a rewrite branch (as well as everything's been updated about a year ago).

Are you still supporting this and is it safe to use in production or has it aged too much?

**Comment by gmmorris** [comment]
Hey Ian,
It should definitely be safe to use in production, I got distracted by
other things so won't be making changes in the near future, but even if I
do I'll respect semver so you should be fine.
